
packages = c(
 'Signac',
 'Seurat',
 'ggplot2',
 'patchwork',
 'SummarizedExperiment',
 #'epiAneufinder',
# 'JASPAR2020',
 'TFBSTools',
 'TxDb.Hsapiens.UCSC.hg38.knownGene',
 'EnsDb.Hsapiens.v86',
 'gplots',
 'regioneR',
 'ComplexHeatmap',
 'ArchR',
 'BSgenome.Hsapiens.UCSC.hg38',
 'tidyverse',
 'ggrepel',
 'RColorBrewer',
 'hdWGCNA',
 'biomaRt',
 'GenomicFeatures',
 'org.Hs.eg.db',
 'rstatix',
 'ggpubr',
 'presto',
 'GSA',
 'clusterProfiler',
 'scales',
 'ggridges',
 'viridis'
)
lapply(packages, require, character.only = TRUE)
